// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5kixSP12A1B9xOU8-g_pXRRNid_BUkE',
    appId: '1:492351428963:web:0dd5745948f4b8c1f11b56',
    messagingSenderId: '492351428963',
    projectId: 'hoteltutorial-b6b4b',
    authDomain: 'hoteltutorial-b6b4b.firebaseapp.com',
    storageBucket: 'hoteltutorial-b6b4b.appspot.com',
    measurementId: 'G-1Z7PMJF11H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogW3nKXoOnmrjqryF6TidygHdnw1EXgA',
    appId: '1:492351428963:android:78dbe80947681919f11b56',
    messagingSenderId: '492351428963',
    projectId: 'hoteltutorial-b6b4b',
    storageBucket: 'hoteltutorial-b6b4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfeDuSA-lC0_usMJx9eTWX8k3AMtosGFk',
    appId: '1:492351428963:ios:788cf4c67abdaf49f11b56',
    messagingSenderId: '492351428963',
    projectId: 'hoteltutorial-b6b4b',
    storageBucket: 'hoteltutorial-b6b4b.appspot.com',
    iosBundleId: 'com.example.hoteltutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfeDuSA-lC0_usMJx9eTWX8k3AMtosGFk',
    appId: '1:492351428963:ios:788cf4c67abdaf49f11b56',
    messagingSenderId: '492351428963',
    projectId: 'hoteltutorial-b6b4b',
    storageBucket: 'hoteltutorial-b6b4b.appspot.com',
    iosBundleId: 'com.example.hoteltutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD5kixSP12A1B9xOU8-g_pXRRNid_BUkE',
    appId: '1:492351428963:web:c68153994421bffef11b56',
    messagingSenderId: '492351428963',
    projectId: 'hoteltutorial-b6b4b',
    authDomain: 'hoteltutorial-b6b4b.firebaseapp.com',
    storageBucket: 'hoteltutorial-b6b4b.appspot.com',
    measurementId: 'G-0W3WG2C4YY',
  );
}
